### ISSUE TITLE
404 NOT FOUND

### ISSUE THREAD

**Issue by moha-b** [AndriaSalah/MyPortfolio#1]
![image](https://github.com/AndriaSalah/MyPortfolio/assets/73842931/a60a50fa-34f9-4639-860c-4b0081bb0f79)

**Comment by AndriaSalah** [comment]
It might be an issue with vercel as it'a working for me right now

**Comment by moha-b** [comment]
check this link pls : [my-portfolio-kappa-ebon.vercel.app](https://my-portfolio-kappa-ebon.vercel.app/)

**Comment by moha-b** [comment]
it works now close the issue
